apiVersion: v1
kind: Service
metadata:
  name: swimlane-app

spec:
  type: {{ .Values.service.type }}

  selector:
    app: swimlane-app

  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
